name: Stage the app

on: 
  pull_request:
    types: [labeled]

env:
    DOCKER_IMAGE_NAME: tomasZayo-azure-ttt
    IMAGE_REGISTRY_URL: docker.pkg.github.com
    #################################################
    ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
    #################################################
    #################################################
    ### REPLACE USERNAME WITH GH USERNAME         ###
    AZURE_WEBAPP_NAME: tomasZayo-ttt-app
    #################################################

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    runs-on: ubuntu-latest
   
